# Generated by Django 5.2.6 on 2025-09-23 12:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson_placeholder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='placeholder_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Placeholder-image'),
        ),
    ]
